export const myTheme = {
    colors: {
        PraymaryText: "#2D2D2D",
        discriptionText: "#6A6A6A",
        descriptionCard: '#929292',
        highlighting: "#E63946",
        Title: "rgba(45, 45, 45, 1)",
        additionalText: "#B8B8B8",
        statusUserText: "#A8A8A8",
        descriptionPostText: "#535353",
        statValueText: "#DDDDDD",
        descriptionFooterText: "#929292",
        BgLightSection: '#FFFFFF',
        BgMainSection: "#F9F9F9",
        BgHeader: "rgba(249, 249, 249, 0.5)",
        secondarySection: "#E5E9ED",
        additionalSection: "#DCDCDC",
        BgBrandsSection: "#FAFAFA",
        bgColorIcon: 'rgba(253, 253, 253, 1)',
        bgIconMain: '#FF7676',
        strokeSecondSection: '#F0F0F0',
        bgHoverPortfolioPost: 'rgba(21, 21, 21, .71)',
        inactiveItem: '#EBEBEB',
        borderColorBtnMain: "#9E9E9E",
        borderBtnGray: "#E1E1E1",
        borderGrandIcon: '#DCDCDC',
        borderFooterBtn: '#5A5A5A',
        whteColor: "#fff",
        arrowColor: 'rgba(159, 159, 159, 0.31)',
        footerLine: '#848484',
    },

    media: {
        mobile: 'screen and (max-width: 576px)',
        tablet: 'screen and (max-width: 768px)',
        large: 'screen and (max-width: 992px)',
        extra_large: 'screen and (max-width: 1200px)',

    }
}